---
name: Run pre-commit for static analysis

"on":
  pull_request: {}
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tool dependencies
        uses: jdx/mise-action@v2
      - uses: pre-commit/action@v3.0.1
